name: "Bug Report"
description: "Reporta un problema o error en el proyecto"
title: "[BUG] Breve descripción del problema"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **¡Gracias por reportar un bug!**  
        Por favor, proporciona la siguiente información para ayudarnos a reproducir y corregir el problema.

  - type: input
    id: title
    attributes:
      label: "Título"
      description: "Describe brevemente el problema"
      placeholder: "Ejemplo: Error al iniciar sesión en la aplicación"
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Descripción"
      description: "Explica el problema en detalle. ¿Qué esperabas que sucediera y qué ocurrió realmente?"
      placeholder: "Describe el problema..."
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severidad"
      description: "Selecciona el nivel de severidad del problema"
      options:
        - Critico
        - Alto
        - Medio
        - Bajo
      required: true

  - type: input
    id: environment
    attributes:
      label: "Entorno"
      description: "Proporciona detalles del entorno donde se produjo el problema (SO, navegador, versión del software, etc.)"
      placeholder: "Ejemplo: Windows 10, Chrome 95, versión 1.0.0 de la app"
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Pasos para reproducir"
      description: "Especifica los pasos para reproducir el error"
      placeholder: |
        1. Ir a...
        2. Hacer clic en...
        3. Observar el error...
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Resultado esperado"
      description: "¿Qué esperabas que sucediera en lugar del error?"
      placeholder: "Ejemplo: El usuario debería poder iniciar sesión sin problemas."

  - type: textarea
    id: actual
    attributes:
      label: "Resultado actual"
      description: "¿Qué sucedió realmente?"
      placeholder: "Describe el resultado que obtuviste."

  - type: textarea
    id: screenshots
    attributes:
      label: "Capturas de pantalla"
      description: "Si es posible, incluye capturas de pantalla para ayudar a identificar el problema"
      placeholder: "Arrastra o sube capturas de pantalla aquí."

  - type: textarea
    id: additional_info
    attributes:
      label: "Información adicional"
      description: "Incluye cualquier otra información que consideres relevante para resolver el problema"
      placeholder: "Comentarios adicionales..."
