# Generated by Django 5.1.4 on 2026-04-25 22:01

import apps.envios.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repartidores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=apps.envios.models._generate_tracking, max_length=20, unique=True, verbose_name='Número de guía')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Borrador')),
                ('sender_name', models.CharField(max_length=150, verbose_name='Nombre remitente')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='Teléfono remitente')),
                ('sender_address', models.CharField(max_length=300, verbose_name='Dirección remitente')),
                ('sender_city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad remitente')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='Nombre destinatario')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Teléfono destinatario')),
                ('recipient_address', models.CharField(max_length=300, verbose_name='Dirección destinatario')),
                ('recipient_city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad destinatario')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Alto (cm)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ancho (cm)')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Profundo (cm)')),
                ('insured_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor asegurado (COP)')),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('prioritario', 'Prioritario'), ('express', 'Express')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('en_bodega', 'En bodega'), ('en_ruta', 'En ruta'), ('en_entrega', 'En entrega'), ('recibido', 'Recibido'), ('incidencia', 'Incidencia')], default='en_bodega', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_creados', to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='repartidores.repartidor')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'envios',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_bodega', 'En bodega'), ('en_ruta', 'En ruta'), ('en_entrega', 'En entrega'), ('recibido', 'Recibido'), ('incidencia', 'Incidencia')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.envio')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'db_table': 'envios_historial',
                'ordering': ('timestamp',),
            },
        ),
    ]
