-- Crear la base de datos
CREATE DATABASE VENTAS;

-- Seleccionar la base de datos
USE VENTAS;

-- Crear la tabla ARTICULO
CREATE TABLE ARTICULO (
    ART_COD   VARCHAR(10) NOT NULL PRIMARY KEY,
    ART_NOM   VARCHAR(50) NOT NULL,
    ART_UNI   VARCHAR(50) NOT NULL,
    ART_PRE   INT NOT NULL,
    ART_STK   INT NOT NULL,
    ART_MARCA VARCHAR(50) NOT NULL
);

-- Insertar registros de ejemplo
INSERT INTO ARTICULO VALUES ("A001", "MEMORIA DDR1", "UNIDAD", 50000, 15, "MARKVISION");
INSERT INTO ARTICULO VALUES ("A002", "MEMORIA DDR2", "UNIDAD", 70000, 10, "MARKVISION");
INSERT INTO ARTICULO VALUES ("A003", "MEMORIA DDR3", "UNIDAD", 100000, 20, "MARKVISION");
INSERT INTO ARTICULO VALUES ("A004", "MEMORIA SIMM", "UNIDAD", 15000, 34, "MARKVISION");
INSERT INTO ARTICULO VALUES ("A005", "MEMORIA DIMM", "UNIDAD", 30000, 15, "MARKVISION");
INSERT INTO ARTICULO VALUES ("A007", "MEMORIA SD", "UNIDAD", 40000, 10, "MARKVISION");
INSERT INTO ARTICULO VALUES ("A006", "MEMORIA CMOS", "UNIDAD", 10000, 22, "MARKVISION");
