# Generated by Django 5.1.4 on 2026-04-25 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('vehicle', models.CharField(choices=[('moto', 'Moto'), ('bicicleta', 'Bicicleta'), ('carro', 'Carro')], default='moto', max_length=20)),
                ('plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'db_table': 'repartidores',
                'ordering': ('name',),
            },
        ),
    ]
