# Generated by Django 5.1.4 on 2026-04-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartidores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartidor',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='plate',
            field=models.CharField(max_length=10, unique=True, verbose_name='Placa'),
        ),
    ]
